-- Real documentation tree for MarkD
-- Complete hierarchical structure with folders and files

-- Clean existing data (keep root)
DELETE FROM documents WHERE id != 'root';

-- Level 1: Main folders
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('folder-getting-started', 'Getting Started', 'folder', 'root', NULL),
('folder-architecture', 'Architecture', 'folder', 'root', NULL),
('folder-api-docs', 'API Documentation', 'folder', 'root', NULL),
('folder-guides', 'Guides', 'folder', 'root', NULL),
('folder-examples', 'Examples', 'folder', 'root', NULL),
('doc-readme', 'README.md', 'file', 'root', '# MarkD Documentation Manager\n\nWelcome to the complete documentation system.\n\n## Features\n\n- Hierarchical document organization\n- Real-time collaboration\n- Markdown editing with preview\n- Drag & drop support\n- Lock system for editing\n- WebSocket synchronization\n\n## Quick Start\n\nCheck the Getting Started folder for installation guides.');

-- Level 2: Getting Started subfolder
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('doc-installation', 'Installation.md', 'file', 'folder-getting-started', '# Installation Guide\n\n## Prerequisites\n\n- Python 3.11+\n- Node.js 18+\n- MySQL 8.0+\n- PM2 (optional)\n\n## Backend Setup\n\n```bash\ncd backend\npip install -r requirements.txt\npython main.py\n```\n\n## Frontend Setup\n\n```bash\ncd frontend\nnpm install\nnpm run dev\n```\n\n## Database\n\n```bash\nmysql markd-v1 < database/schema.sql\n```'),
('doc-quickstart', 'Quickstart.md', 'file', 'folder-getting-started', '# Quick Start\n\n## 1. Start with PM2\n\n```bash\npm2 start ecosystem.config.js\n```\n\n## 2. Access the Application\n\nhttps://markd-v1.c9.ooo.ovh\n\n## 3. Create Your First Document\n\n1. Click on "Add Document" in the root folder\n2. Enter a name\n3. Start editing!\n\n## 4. Organize\n\n- Create folders for organization\n- Drag & drop to move documents\n- Upload existing markdown files'),
('doc-configuration', 'Configuration.md', 'file', 'folder-getting-started', '# Configuration\n\n## Environment Variables\n\nEdit `backend/.env`:\n\n```env\nDB_HOST=localhost\nDB_PORT=3306\nDB_NAME=markd-v1\nDB_USER=markd-v1\nDB_PASSWORD=your_password\nAPI_PORT=4567\nCORS_ORIGINS=http://localhost:5173\n```\n\n## Nginx\n\nConfiguration file: `/etc/nginx/sites-enabled/10-markd-v1.conf`\n\n## PM2\n\nProcess configuration: `ecosystem.config.js`');

-- Level 2: Architecture subfolder
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('folder-backend', 'Backend', 'folder', 'folder-architecture', NULL),
('folder-frontend', 'Frontend', 'folder', 'folder-architecture', NULL),
('folder-database', 'Database', 'folder', 'folder-architecture', NULL),
('doc-system-overview', 'System-Overview.md', 'file', 'folder-architecture', '# System Architecture Overview\n\n## Components\n\n### Backend (FastAPI)\n- Port: 4567\n- Framework: FastAPI\n- WebSocket: python-socketio\n- Database: PyMySQL\n\n### Frontend (React)\n- Port: 5173\n- Framework: React 18 + TypeScript\n- Bundler: Vite\n- UI: TailwindCSS\n\n### MCP Server\n- Port: 4568\n- Purpose: AI Agent integration\n\n### Infrastructure\n- Nginx: Reverse proxy + SSL\n- PM2: Process manager\n- MySQL: Database\n\n## Data Flow\n\n```\nUser → Nginx → Frontend → API → MySQL\n         ↓                    ↓\n    WebSocket ←→ Socket.IO ←→ Broadcast\n```');

-- Level 3: Backend architecture
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('doc-backend-api', 'REST-API.md', 'file', 'folder-backend', '# Backend REST API\n\n## Endpoints\n\n### Documents\n- `GET /api/documents/tree` - Get full tree\n- `GET /api/documents/{id}` - Get single document\n- `POST /api/documents` - Create document/folder\n- `PUT /api/documents/{id}` - Update document\n- `DELETE /api/documents/{id}` - Delete document\n- `POST /api/documents/{id}/move` - Move document\n- `POST /api/documents/{id}/copy` - Copy document\n\n### Locks\n- `POST /api/documents/{id}/lock` - Lock document\n- `DELETE /api/documents/{id}/lock` - Unlock document\n\n### MCP\n- `POST /api/mcp/log` - Log agent activity\n- `GET /api/mcp/activity` - Get activity log'),
('doc-backend-websocket', 'WebSocket-Events.md', 'file', 'folder-backend', '# WebSocket Events\n\n## Server → Client\n\n### tree_updated\nBroadcast when tree structure changes\n```json\n{\n  "tree": [...]\n}\n```\n\n### lock_updated\nBroadcast when document lock changes\n```json\n{\n  "document_id": "doc-123",\n  "locked_by": {\n    "user_id": "user-456",\n    "user_name": "John"\n  }\n}\n```\n\n### user_editing\nNotify when user starts editing\n```json\n{\n  "document_id": "doc-123",\n  "user_name": "John"\n}\n```\n\n## Client → Server\n\n### request_tree\nRequest full tree update\n\n### document_editing\nNotify server of editing activity');

-- Level 3: Frontend architecture
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('doc-frontend-components', 'Components.md', 'file', 'folder-frontend', '# Frontend Components\n\n## App.tsx\nMain application component\n- State management\n- WebSocket connection\n- Session storage\n- Drag & drop context\n\n## DocumentTree.tsx\nHierarchical tree view\n- Recursive rendering\n- Drag & drop support\n- Context menu actions\n- Lock indicators\n\n## DocumentViewer.tsx\nRead-only markdown viewer\n- React-markdown rendering\n- Lock status display\n- Edit button\n\n## DocumentEditor.tsx\nSplit-view editor\n- Live markdown preview\n- Auto-save on edit\n- Lock on edit start'),
('doc-frontend-services', 'Services.md', 'file', 'folder-frontend', '# Frontend Services\n\n## api.ts\nREST API client\n- Fetch wrapper\n- Type-safe requests\n- Error handling\n\n## websocket.ts\nWebSocket service\n- Socket.IO client\n- Event subscriptions\n- Auto-reconnect\n\n## sessionStorage.ts\nUI state persistence\n- Save expanded nodes\n- Save selected document\n- Load on page refresh'),
('doc-frontend-types', 'TypeScript-Types.md', 'file', 'folder-frontend', '# TypeScript Types\n\n## Document\n```typescript\ninterface Document {\n  id: string;\n  name: string;\n  type: "file" | "folder";\n  content?: string;\n  parent_id: string | null;\n  created_at?: string;\n  updated_at?: string;\n  children?: Document[];\n  locked_by?: LockInfo | null;\n}\n```\n\n## SessionState\n```typescript\ninterface SessionState {\n  expandedNodes: Record<string, boolean>;\n  selectedId: string | null;\n}\n```\n\n## LockInfo\n```typescript\ninterface LockInfo {\n  user_id: string;\n  user_name: string;\n}\n```');

-- Level 3: Database architecture
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('doc-db-schema', 'Schema.md', 'file', 'folder-database', '# Database Schema\n\n## documents\nMain documents and folders table\n- `id` VARCHAR(36) PRIMARY KEY\n- `name` VARCHAR(255) - Document name\n- `type` ENUM("file", "folder")\n- `content` LONGTEXT - Markdown content\n- `parent_id` VARCHAR(36) - Parent folder\n- `created_at`, `updated_at` TIMESTAMP\n\n## document_locks\nCollaborative editing locks\n- `document_id` VARCHAR(36) PRIMARY KEY\n- `user_id` VARCHAR(255)\n- `user_name` VARCHAR(255)\n- `locked_at` TIMESTAMP\n\n## session_states\nUI state persistence\n- `session_id` VARCHAR(255) PRIMARY KEY\n- `user_id` VARCHAR(255)\n- `expanded_nodes` JSON\n- `selected_id` VARCHAR(36)\n\n## mcp_activity_log\nAI agent activity tracking\n- `id` INT AUTO_INCREMENT\n- `agent_id` VARCHAR(255)\n- `action` VARCHAR(100)\n- `document_id` VARCHAR(36)\n- `details` JSON\n- `created_at` TIMESTAMP'),
('doc-db-queries', 'Common-Queries.md', 'file', 'folder-database', '# Common Database Queries\n\n## Get all documents\n```sql\nSELECT * FROM documents ORDER BY type DESC, name ASC;\n```\n\n## Get tree structure\n```sql\nSELECT id, name, type, parent_id \nFROM documents \nWHERE parent_id = "root";\n```\n\n## Check locks\n```sql\nSELECT d.name, l.user_name, l.locked_at\nFROM documents d\nJOIN document_locks l ON d.id = l.document_id;\n```\n\n## Get MCP activity\n```sql\nSELECT * FROM mcp_activity_log\nORDER BY created_at DESC\nLIMIT 50;\n```');

-- Level 2: API Documentation
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('folder-rest-api', 'REST API', 'folder', 'folder-api-docs', NULL),
('folder-mcp-api', 'MCP API', 'folder', 'folder-api-docs', NULL),
('folder-websocket-api', 'WebSocket API', 'folder', 'folder-api-docs', NULL);

-- Level 3: REST API docs
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('doc-api-documents', 'Documents-Endpoints.md', 'file', 'folder-rest-api', '# Documents API\n\n## GET /api/documents/tree\nGet complete document tree\n\n**Response:**\n```json\n{\n  "success": true,\n  "tree": [\n    {\n      "id": "doc-1",\n      "name": "Guide.md",\n      "type": "file",\n      "content": "...",\n      "locked_by": null,\n      "children": []\n    }\n  ]\n}\n```\n\n## POST /api/documents\nCreate new document\n\n**Request:**\n```json\n{\n  "name": "My Document.md",\n  "type": "file",\n  "parent_id": "root",\n  "content": "# My Document"\n}\n```'),
('doc-api-locks', 'Lock-Endpoints.md', 'file', 'folder-rest-api', '# Lock API\n\n## POST /api/documents/{id}/lock\nLock document for editing\n\n**Request:**\n```json\n{\n  "user_id": "user-123",\n  "user_name": "John Doe"\n}\n```\n\n**Response (success):**\n```json\n{\n  "success": true,\n  "message": "Document locked"\n}\n```\n\n**Response (already locked):**\n```json\n{\n  "success": false,\n  "message": "Document already locked",\n  "locked_by": {\n    "user_id": "user-456",\n    "user_name": "Jane"\n  }\n}\n```\n\n## DELETE /api/documents/{id}/lock?user_id=xxx\nUnlock document\n\n**Response:**\n```json\n{\n  "success": true,\n  "message": "Document unlocked"\n}\n```'),
('doc-api-operations', 'Operations.md', 'file', 'folder-rest-api', '# Document Operations\n\n## Move Document\n```bash\ncurl -X POST http://localhost:4567/api/documents/{id}/move \\\n  -H "Content-Type: application/json" \\\n  -d ''{"parent_id": "new-parent-id"}''\n```\n\n## Copy Document\n```bash\ncurl -X POST http://localhost:4567/api/documents/{id}/copy\n```\n\n## Update Document\n```bash\ncurl -X PUT http://localhost:4567/api/documents/{id} \\\n  -H "Content-Type: application/json" \\\n  -d ''{"name": "New Name.md", "content": "# Updated"}''\n```\n\n## Delete Document\n```bash\ncurl -X DELETE http://localhost:4567/api/documents/{id}\n```');

-- Level 3: MCP API docs  
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('doc-mcp-overview', 'MCP-Overview.md', 'file', 'folder-mcp-api', '# MCP Server Overview\n\n## Purpose\n\nAllow AI agents to automatically document their work.\n\n## Port\n\n4568\n\n## Base URL\n\nhttp://localhost:4568/mcp/\n\n## Features\n\n- Create documents via API\n- Append content to existing docs\n- Search documentation\n- Track agent activity\n- Organize into folders\n\n## Authentication\n\nCurrently no auth (internal use only)'),
('doc-mcp-endpoints', 'MCP-Endpoints.md', 'file', 'folder-mcp-api', '# MCP API Endpoints\n\n## POST /mcp/documents\nCreate document via AI agent\n\n**Request:**\n```json\n{\n  "agent_id": "agent-123",\n  "agent_name": "Documentation Bot",\n  "title": "API Guide",\n  "content": "# API Guide\\n\\nComplete documentation...",\n  "parent_folder": "root",\n  "tags": ["api", "guide"]\n}\n```\n\n## POST /mcp/documents/{id}/append\nAppend content to existing document\n\n## POST /mcp/search\nSearch documents\n\n## GET /mcp/activity\nGet agent activity log\n\n## POST /mcp/folders\nCreate folder structure');

-- Level 2: Guides
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('folder-user-guides', 'User Guides', 'folder', 'folder-guides', NULL),
('folder-dev-guides', 'Developer Guides', 'folder', 'folder-guides', NULL),
('folder-admin-guides', 'Admin Guides', 'folder', 'folder-guides', NULL);

-- Level 3: User Guides
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('doc-user-editing', 'Editing-Documents.md', 'file', 'folder-user-guides', '# How to Edit Documents\n\n## Read Mode\n\n1. Click on any document in the tree\n2. View the rendered markdown\n\n## Edit Mode\n\n1. Click the "Edit" button\n2. Document gets locked automatically\n3. Edit in the left pane\n4. See live preview on the right\n5. Click "Save" to save changes\n6. Document is automatically unlocked\n\n## Locked Documents\n\nIf a document shows a 🔒 icon, someone else is editing it.\nWait for them to finish or contact them.'),
('doc-user-organizing', 'Organizing-Documents.md', 'file', 'folder-user-guides', '# Organizing Your Documentation\n\n## Creating Folders\n\n1. Hover over any folder\n2. Click the folder icon (+)\n3. Enter folder name\n\n## Moving Documents\n\n### Method 1: Drag & Drop\n- Click and hold on a document\n- Drag to the target folder\n- Release to drop\n\n### Method 2: API\nUse the move endpoint\n\n## Creating Documents\n\n1. Hover over a folder\n2. Click the + icon\n3. Enter document name\n4. Start editing!\n\n## Tips\n\n- Use folders for logical grouping\n- Keep folder depth reasonable (max 5 levels)\n- Use descriptive names\n- Add .md extension for markdown files'),
('doc-user-collaboration', 'Collaboration.md', 'file', 'folder-user-guides', '# Collaborative Editing\n\n## Lock System\n\nMarkD uses a lock system to prevent conflicts:\n\n1. When you click "Edit", the document is locked\n2. Other users see a 🔒 icon\n3. They cannot edit until you save or cancel\n4. Lock is released automatically\n\n## Real-time Updates\n\nAll users see changes immediately:\n- New documents appear\n- Deleted documents disappear\n- Moved documents update position\n- Lock status updates in real-time\n\n## Best Practices\n\n- Edit one document at a time\n- Save frequently\n- Use descriptive commit messages\n- Communicate with team in chat');

-- Level 3: Developer Guides
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('doc-dev-setup', 'Development-Setup.md', 'file', 'folder-dev-guides', '# Development Environment Setup\n\n## IDE Recommended\n\n- VSCode with extensions:\n  - Python\n  - ESLint\n  - Prettier\n  - Tailwind CSS IntelliSense\n\n## Backend Development\n\n```bash\ncd backend\npython main.py\n```\n\nAPI auto-reloads on file changes (uvicorn --reload)\n\n## Frontend Development\n\n```bash\ncd frontend\nnpm run dev\n```\n\nVite HMR (Hot Module Replacement) enabled\n\n## Database Changes\n\n```bash\nmysql markd-v1 < database/schema.sql\npm2 restart markd-backend\n```'),
('doc-dev-testing', 'Testing.md', 'file', 'folder-dev-guides', '# Testing Guide\n\n## Manual Testing\n\n1. Start all services\n2. Open http://localhost:5173\n3. Test each feature:\n   - Create document\n   - Edit document\n   - Move with drag & drop\n   - Upload file\n   - Download file\n   - Lock/unlock\n\n## API Testing\n\n```bash\n# Test tree endpoint\ncurl http://localhost:4567/api/documents/tree\n\n# Test create\ncurl -X POST http://localhost:4567/api/documents \\\n  -H "Content-Type: application/json" \\\n  -d ''{"name": "Test.md", "type": "file", "parent_id": "root"}''\n```\n\n## WebSocket Testing\n\nOpen browser console:\n```javascript\nconst socket = io();\nsocket.on("tree_updated", console.log);\n```'),
('doc-dev-contributing', 'Contributing.md', 'file', 'folder-dev-guides', '# Contributing to MarkD\n\n## Code Style\n\n### Backend (Python)\n- Follow PEP 8\n- Use type hints\n- Add docstrings\n- Keep functions small\n\n### Frontend (TypeScript)\n- Use TypeScript strict mode\n- Functional components only\n- Use hooks (useState, useEffect, useCallback)\n- Props destructuring\n\n## Git Workflow\n\n1. Create feature branch\n2. Make changes\n3. Test locally\n4. Commit with clear message\n5. Push and create PR\n\n## Commit Messages\n\n```\nfeat: Add drag & drop support\nfix: Resolve recursion error in tree\ndocs: Update API documentation\nrefactor: Split App into components\n```');

-- Level 3: Admin Guides
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('doc-admin-deployment', 'Deployment.md', 'file', 'folder-admin-guides', '# Deployment Guide\n\n## Production Deployment\n\n### 1. Server Setup\n\n```bash\n# Install dependencies\napt update\napt install python3 python3-pip nodejs npm nginx mysql-server\nnpm install -g pm2\n```\n\n### 2. Clone Project\n\n```bash\ngit clone <repo>\ncd markd-v1/app\n```\n\n### 3. Configure\n\n```bash\n# Backend\ncd backend\npip install -r requirements.txt\ncp .env.example .env\n# Edit .env with production values\n\n# Frontend\ncd ../frontend\nnpm install\n```\n\n### 4. Database\n\n```bash\nmysql -u root -p\nCREATE DATABASE markd_v1;\nCREATE USER ''markd_v1''@''localhost'' IDENTIFIED BY ''password'';\nGRANT ALL ON markd_v1.* TO ''markd_v1''@''localhost'';\nexit\n\nmysql markd_v1 < database/schema.sql\n```\n\n### 5. Start with PM2\n\n```bash\npm2 start ecosystem.config.js\npm2 save\npm2 startup\n```'),
('doc-admin-monitoring', 'Monitoring.md', 'file', 'folder-admin-guides', '# System Monitoring\n\n## PM2 Monitoring\n\n```bash\n# Process status\npm2 status\n\n# Live monitoring\npm2 monit\n\n# Logs\npm2 logs\npm2 logs markd-backend\n\n# Restart if needed\npm2 restart all\n```\n\n## Nginx Logs\n\n```bash\ntail -f /var/log/nginx/access.log\ntail -f /var/log/nginx/error.log\n```\n\n## Database Monitoring\n\n```bash\n# Active connections\nmysql markd-v1 -e "SHOW PROCESSLIST;"\n\n# Table sizes\nmysql markd-v1 -e "SELECT table_name, \n  ROUND(((data_length + index_length) / 1024 / 1024), 2) AS Size_MB \n  FROM information_schema.TABLES \n  WHERE table_schema = ''markd-v1'';"\n```\n\n## Disk Usage\n\n```bash\ndf -h\ndu -sh /apps/markd-v1/app/*\n```'),
('doc-admin-backup', 'Backup-Recovery.md', 'file', 'folder-admin-guides', '# Backup and Recovery\n\n## Database Backup\n\n### Daily Backup\n```bash\nmysqldump markd-v1 > backup-$(date +%Y%m%d).sql\n```\n\n### Automated Backup (crontab)\n```bash\n# Daily at 2 AM\n0 2 * * * mysqldump markd-v1 > /backups/markd-$(date +\\%Y\\%m\\%d).sql\n```\n\n### Restore\n```bash\nmysql markd-v1 < backup-20251008.sql\npm2 restart all\n```\n\n## Code Backup\n\n```bash\ngit push origin main\n```\n\n## Full System Backup\n\n```bash\ntar -czf markd-full-$(date +%Y%m%d).tar.gz \\\n  /apps/markd-v1/app \\\n  /etc/nginx/sites-enabled/10-markd-v1.conf\n```');

-- Level 2: Examples
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('folder-code-examples', 'Code Examples', 'folder', 'folder-examples', NULL),
('folder-use-cases', 'Use Cases', 'folder', 'folder-examples', NULL);

-- Level 3: Code Examples
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('doc-example-python', 'Python-Client.md', 'file', 'folder-code-examples', '# Python API Client Example\n\n```python\nimport requests\n\nBASE_URL = "http://localhost:4567/api"\n\nclass MarkDClient:\n    def get_tree(self):\n        response = requests.get(f"{BASE_URL}/documents/tree")\n        return response.json()\n    \n    def create_document(self, name, content, parent_id="root"):\n        data = {\n            "name": name,\n            "type": "file",\n            "parent_id": parent_id,\n            "content": content\n        }\n        response = requests.post(f"{BASE_URL}/documents", json=data)\n        return response.json()\n    \n    def lock_document(self, doc_id, user_id, user_name):\n        data = {"user_id": user_id, "user_name": user_name}\n        response = requests.post(\n            f"{BASE_URL}/documents/{doc_id}/lock",\n            json=data\n        )\n        return response.json()\n\n# Usage\nclient = MarkDClient()\ntree = client.get_tree()\nprint(f"Documents: {len(tree[''tree''])}")\n```'),
('doc-example-javascript', 'JavaScript-Client.md', 'file', 'folder-code-examples', '# JavaScript API Client Example\n\n```javascript\nclass MarkDClient {\n  constructor(baseUrl = ''/api'') {\n    this.baseUrl = baseUrl;\n  }\n\n  async getTree() {\n    const res = await fetch(`${this.baseUrl}/documents/tree`);\n    return res.json();\n  }\n\n  async createDocument(name, content, parentId = ''root'') {\n    const res = await fetch(`${this.baseUrl}/documents`, {\n      method: ''POST'',\n      headers: { ''Content-Type'': ''application/json'' },\n      body: JSON.stringify({\n        name,\n        type: ''file'',\n        parent_id: parentId,\n        content\n      })\n    });\n    return res.json();\n  }\n\n  async lockDocument(docId, userId, userName) {\n    const res = await fetch(\n      `${this.baseUrl}/documents/${docId}/lock`,\n      {\n        method: ''POST'',\n        headers: { ''Content-Type'': ''application/json'' },\n        body: JSON.stringify({ user_id: userId, user_name: userName })\n      }\n    );\n    return res.json();\n  }\n}\n\n// Usage\nconst client = new MarkDClient();\nconst tree = await client.getTree();\nconsole.log(tree);\n```'),
('doc-example-curl', 'cURL-Examples.md', 'file', 'folder-code-examples', '# cURL API Examples\n\n## Get Tree\n```bash\ncurl http://localhost:4567/api/documents/tree | jq\n```\n\n## Create Document\n```bash\ncurl -X POST http://localhost:4567/api/documents \\\n  -H "Content-Type: application/json" \\\n  -d ''{\n    "name": "New Doc.md",\n    "type": "file",\n    "parent_id": "root",\n    "content": "# Hello World"\n  }'' | jq\n```\n\n## Lock Document\n```bash\ncurl -X POST http://localhost:4567/api/documents/doc-123/lock \\\n  -H "Content-Type: application/json" \\\n  -d ''{\n    "user_id": "user-1",\n    "user_name": "John"\n  }'' | jq\n```\n\n## Move Document\n```bash\ncurl -X POST http://localhost:4567/api/documents/doc-123/move \\\n  -H "Content-Type: application/json" \\\n  -d ''{"parent_id": "folder-456"}'' | jq\n```\n\n## Delete Document\n```bash\ncurl -X DELETE http://localhost:4567/api/documents/doc-123\n```');

-- Level 3: Use Cases
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('doc-usecase-technical', 'Technical-Documentation.md', 'file', 'folder-use-cases', '# Use Case: Technical Documentation\n\n## Scenario\n\nSoftware development team needs centralized technical docs.\n\n## Organization Structure\n\n```\nRoot/\n├── Architecture/\n│   ├── System-Design.md\n│   ├── Database-Schema.md\n│   └── API-Specs.md\n├── Development/\n│   ├── Setup-Guide.md\n│   ├── Code-Standards.md\n│   └── Testing.md\n└── Deployment/\n    ├── Production.md\n    └── Monitoring.md\n```\n\n## Benefits\n\n- Single source of truth\n- Real-time collaboration\n- Version history (via backups)\n- Easy navigation\n- Markdown formatting'),
('doc-usecase-knowledge', 'Knowledge-Base.md', 'file', 'folder-use-cases', '# Use Case: Knowledge Base\n\n## Scenario\n\nCompany wants to centralize all knowledge and procedures.\n\n## Organization\n\n```\nRoot/\n├── HR/\n│   ├── Onboarding.md\n│   ├── Policies.md\n│   └── Benefits.md\n├── IT/\n│   ├── Network-Setup.md\n│   ├── Troubleshooting.md\n│   └── Security.md\n├── Sales/\n│   ├── Process.md\n│   ├── Scripts.md\n│   └── CRM-Guide.md\n└── Support/\n    ├── FAQ.md\n    ├── Common-Issues.md\n    └── Escalation.md\n```\n\n## Features Used\n\n- Folder organization by department\n- Easy search (coming soon)\n- Upload existing docs\n- Collaborative editing\n- Lock system prevents conflicts'),
('doc-usecase-project', 'Project-Documentation.md', 'file', 'folder-use-cases', '# Use Case: Project Documentation\n\n## Scenario\n\nAgile team documenting sprint work and decisions.\n\n## Organization\n\n```\nRoot/\n├── Sprint-01/\n│   ├── Planning.md\n│   ├── Tasks.md\n│   └── Retrospective.md\n├── Sprint-02/\n│   ├── Planning.md\n│   └── Tasks.md\n├── Architecture-Decisions/\n│   ├── ADR-001-Database.md\n│   ├── ADR-002-Frontend.md\n│   └── ADR-003-Authentication.md\n└── Meeting-Notes/\n    ├── 2025-01-15.md\n    ├── 2025-01-22.md\n    └── 2025-01-29.md\n```\n\n## Workflow\n\n1. Create folder for each sprint\n2. Document planning and decisions\n3. Track progress\n4. Archive completed sprints\n5. MCP server logs AI agent contributions');

-- Additional root-level documents
INSERT INTO documents (id, name, type, parent_id, content) VALUES
('doc-changelog', 'CHANGELOG.md', 'file', 'root', '# Changelog\n\n## Version 1.0.0 - 2025-10-08\n\n### Added\n- Complete document management system\n- Hierarchical tree structure\n- Drag & drop support\n- Real-time collaboration with locks\n- WebSocket synchronization\n- Session storage for UI persistence\n- MCP server for AI agents\n- MCP Playwright for automation\n- PM2 process management\n- Comprehensive documentation\n\n### Features\n- Backend: FastAPI + Socket.IO\n- Frontend: React + TypeScript + Vite\n- Database: MySQL/MariaDB\n- Infrastructure: Nginx + SSL + PM2\n\n### Documentation\n- Complete API reference\n- User guides\n- Developer guides\n- Admin guides\n- Examples and use cases'),
('doc-license', 'LICENSE.md', 'file', 'root', '# MIT License\n\nCopyright (c) 2025 MarkD Project\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the "Software"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.');